language: erlang

otp_release:
  - 17.1
  - 18.3
  - 19.2
  - 20.0

install:
  - sudo apt-get -qq install librsync-dev

script:
  - ./configure
  - make
  - make doc
  - make xref
  - make test

notifications:
  email: false
